eos-diagnostics: Add some more information to the output
endlessm/eos-meta pull request #662
Opened 2020-12-02 22:41 UTC by ManMower

For some issues, debugging is assisted by having a list of EFI variables
and their contents.

Additionally, let's dump the secure boot key and some rudimentary PAYG
information.

https://phabricator.endlessm.com/T31142

2020-12-16 02:45 UTC, jprvita requested changes

2020-12-16 02:45 UTC, jprvita commented on eos-tech-support/eos-diagnostics
> +
Some payg image filenames do not start with "payg", but have "payg" as part of the personality string.

That said, we don't need to try to identify a payg image, we can try to fetch this information on all systems.

2020-12-16 18:20 UTC, ManMower commented
Forced push rebases, and removes the check for payg image

2020-12-17 21:48 UTC, jprvita approved these changes

2020-12-17 21:48 UTC, merged